name = "pcc-worker-cron-trigger"
main = "src/index.ts"
compatibility_date = "2024-05-21"

[vars]
PAGES_FUNCTION_URL = "https://<YOUR_PAGES_PROJECT_NAME>.pages.dev/regenerate-assets"
# CRON_SECRET = "<YOUR_CRON_SECRET>" # Uncomment and set a strong secret if you implement secret-based authentication

[triggers]
# Example: Run every day at 3 AM UTC. Adjust as needed.
# See https://developers.cloudflare.com/workers/wrangler/configuration/#triggers
crons = ["0 3 * * *"]

[observability.logs]
enabled = true
